// task-1b-landing-page-smkdev/src/components/Navbar.vue
<script setup>

</script>

<template>
    <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
        <div class="container">
            <img src="./assets/images/smkdev-logo.png" style="width: 100px;"/>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-lg-flex justify-content-lg-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Learn</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Community</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Blog</a>
                    </li>
                    <li class="nav-item d-flex justify-content-center justify-content-lg-start">
                        <button class="nav-link text-white fw-semibold px-3 ms-lg-3" style="border: 1px solid; border-radius: 10px; background: rgb(23,205,72);
background: linear-gradient(144deg, rgba(23,205,72,1) 45%, rgba(255,193,107,1) 88%);">Dashboard</button>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</template>

// task-1b/src/components/Navbar.jsx
import Container from "react-bootstrap/Container";
import Nav from "react-bootstrap/Nav";
import Navbar from "react-bootstrap/Navbar";
import Button from "react-bootstrap/Button";

function NavComponent() {
  return (
    <Navbar expand="lg" className="bg-body-transparant border-bottom">
      <Container>
        <Navbar.Brand href="#home">
          <img src="https://smkdev.storage.googleapis.com/wp/SMKDEV-Logo-Long-150x38.png" height={35} alt="" />
        </Navbar.Brand>
        <Navbar.Toggle aria-controls="basic-navbar-nav" />
        <Navbar.Collapse id="basic-navbar-nav">
          <Nav className="ms-auto gap-3 ">
            <Nav.Link href="#home" className="text-prim fw-semibold ">
              Learn
            </Nav.Link>
            <Nav.Link href="https://t.me/+xZ2kQTlLPMA1NjJl" target="_blank" className="text-prim fw-semibold">
              Community
            </Nav.Link>
            <Nav.Link href="https://www.smk.dev/blog/" target="_blank" className="text-prim fw-semibold">
              Blog
            </Nav.Link>
            <Nav.Link target="_blank" className="text-prim fw-semibold">
              FAQ
            </Nav.Link>
            <a href="https://lms.smk.dev/login" target="_blank" className="btn btn-primary px-4 bg-prim">
              Login
            </a>
          </Nav>
        </Navbar.Collapse>
      </Container>
    </Navbar>
  );
}

export default NavComponent;
