// frontend-smkdev-task-1b/src/components/Contact.svelte
<script>
    // 
</script>
  <div class="z-10 container mx-auto">
    <div class="flex flex-wrap">
      <div class="w-full md:w-1/2 px-6">
        <div class="flex flex-col justify-between h-full">
          <div class="mb-5 md:max-w-md block">
              <h2 class="text-xl md:text-3xl xl:text-4xl font-bold font-heading tracking-px-n leading-none">Kontak SMKDEV.</h2>
              <p class="mb-6 text-sm text-indigo-600 font-bold uppercase tracking-px">Contact us</p>
              <p class="mb-6 text-sm">Berapa investasi untuk menggunakan SMKDEV? Anda bisa mulai dengan 
               <span class="font-bold"> GRATIS.</span></p>
              <p class="mb-6 text-sm">Silahkan isi form disebelah untuk informasi lebih lanjut.</p>
          </div>    
        </div>
      </div>
      <div class="w-full md:w-1/2">
        <form class="px-6 bg-opacity-80 md:max-w-xl ml-auto rounded-4xl shadow-12xl">
          <label class="block mb-4">
            <p class="mb-2 text-gray-900 font-semibold leading-normal">Nama</p>
            <div class="relative">
              <input class="pl-3 pr-4 py-3 w-full text-gray-500 font-medium placeholder-gray-500 outline-none border border-gray-300 rounded-md focus:ring focus:ring-indigo-300" id="contactInput3-1" type="text" placeholder="First & last name" required>
            </div>
          </label>
          <label class="block mb-4">
            <p class="mb-2 text-gray-900 font-semibold leading-normal">Email</p>
            <div class="relative">
              <input class="pl-3 py-3 w-full text-gray-500 font-medium placeholder-gray-500 outline-none border border-gray-300 rounded-lg focus:ring focus:ring-indigo-300" id="contactInput3-2" type="text" placeholder="Email address" required>
            </div>
          </label>
          <label class="block">
            <p class="mb-2 text-gray-900 font-semibold leading-normal">Pesan</p>
            <div class="relative">
              <textarea class="mb-6 p-4 w-full h-48 font-medium text-gray-500 outline-none placeholder-gray-500 border border-gray-300 resize-none rounded-md focus:ring focus:ring-indigo-300" id="contactInput3-3" placeholder="Write message" required></textarea>
              <div class="md:inline-block">
                <button class="py-2 px-5 lg:w-full text-white font-semibold bg-violet-900 rounded-md  " type="button">Send Message</button>
              </div>
            </div>
          </label>
        </form>
      </div>
    </div>
  </div>

// frontend/smkdev-landing-page/src/sections/contact.tsx
import { ContactForm, MediaQuery } from "@/components";
import { NextPage } from "next";

interface Props {}

const Contact: NextPage<Props> = ({}) => {
  return (
    <div className="bg-bg2 flex w-full justify-center py-20">
      <MediaQuery className="flex flex-col items-center gap-x-10 lg:flex-row lg:items-start lg:justify-between">
        <div className="mb-20 flex w-full flex-col gap-y-5 lg:w-1/2">
          <h1 className="text-3xl font-semibold text-primary">Kontak SMKDEV</h1>
          <p>
            Berapa investasi untuk menggunakan SMKDEV? Anda bisa mulai dengan{" "}
            <span className="font-bold">GRATIS</span>.
          </p>
          <p>Silahkan isi form disebelah untuk informasi lebih lanjut.</p>
        </div>

        <div className="w-full lg:w-1/2">
          <ContactForm />
        </div>
      </MediaQuery>
    </div>
  );
};

export default Contact;
