// smkdev-landing-task1b/src/components/Hero.jsx
import HeroImage from '../assets/hero-image.jpg'

const Hero = () => {
    return (
        <>
            <div className='flex flex-col md:flex-row justify-around mt-6 items-center w-screen gap-4 p-10'>
                <div>
                    <h1 className='md:text-5xl text-3xl font-bold leading-tight'>Siapkan Karir Digital Unggulan Anda</h1>
                    <h1 className='font-medium text-xs md:text-[17px] mt-4 leading-tight'>Ikuti pelatihan langsung dengan profesional berpengalaman dan kembangkan keterampilan dengan kurikulum berbasis proyek yang mendalam</h1>
                    <img className='h-[290px] mt-4 rounded-3xl md:hidden' src={HeroImage}/>
                    <a className='text-[16px] font-medium px-4 py-3 bg-black md:inline-block text-white mt-3 text-center rounded-xl block' href='#'>Get Started</a>
                </div>
                <img className='h-[420px] rounded-3xl hidden md:block' src={HeroImage}/>
            </div>
        </>
    )
}

export default Hero

// task-1b-landing-page-smkdev/src/components/Hero.vue
<script setup>
</script>

<template>
    <div class="row">
        <div class="col-md-6 d-flex align-items-center">
            <div>
                <h1 class="fw-bold text-center text-md-start">Menuju Masa Depan Digital yang Cemerlang</h1>
                <p class="fs-5 text-center text-md-start">Belajar langsung dari pakar industri dengan pendekatan
                    pembelajaran berbasis proyek yang inovatif dan komprehensif.</p>
            </div>
        </div>
        <div class="col-md-6 d-flex justify-content-center">
            <img src="@/components/assets/images/image-1.png" style="width:300px" class="image-foreground"/>
        </div>
    </div>
</template>
