// slicing-smkdev/src/Feature/Navbar/index.jsx
import smkdev from '../../assets/smkdev.png'
// import { DownOutlined } from '@ant-design/icons';
import { Dropdown, Space, Typography } from 'antd';
const Navbar = () => {
    const items = [
        { id:1, key:'1', title:"Learn", label:["Bootcamp", "Expert Class", "Challenges"]}, { id:2, key:'2', title:"Community"}, { id:3, key:'3', title:"Blog"},
    ]
    return (
        <div>
            <div className="py-2 px-4 border-b-2">
                    <div className="flex container mx-auto px-32 flex justify-between items-center">
                    <div className="w-[120px]">
                        <img src={smkdev} alt="smkdev"/>
                    </div>
                    <div>
                        <ul className="flex gap-8 flex items-center cursor-pointer">
                            {items.map((item) => (
                                <div key={item.id}>
                                    <li className='text-base text-sky-950 font-semibold hover:underline underline-offset-8'>
                                        {item.id === 1 ? (
                                            <Dropdown
                                                menu={{
                                                items: item.label.map((label) => ({
                                                key: label,
                                                label,
                                              })),
                                              selectable: true,
                                            }}
                                            className='text-base text-sky-950 font-semibold hover:underline underline-offset-8'
                                          >
                                            <Space>{item.title}</Space>
                                          </Dropdown>
                                            ) : (
                                            item.title
                                        )}
                                    </li>
                                </div>
                            ))}
                            <li>
                                <button className="bg-sky-950 text-white px-6 py-2 rounded-lg text-sm font-semibold">Dashboard</button>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    )
}   


export default Navbar

// src/components/NavBar.vue
<script setup lang="ts">
import MenuIcon from './icons/MenuIcon.vue'
</script>
<template>
  <header class="navbar border-b shadow px-0 md:px-20">
    <div class="dropdown md:hidden">
      <div tabindex="0" role="button" class="btn btn-ghost btn-circle">
        <MenuIcon />
      </div>
      <ul
        tabindex="0"
        class="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] mt-3 w-52 p-2 shadow-xl"
      >
        <li><a>Learn</a></li>
        <li><a>Community</a></li>
        <li><a>Blog</a></li>
      </ul>
    </div>
    <div class="flex-1">
      <a class="btn btn-ghost pl-0">
        <img src="/logo/smkdev-logo.png" alt="logo smkdev" width="120" />
      </a>
    </div>
    <div class="flex-none">
      <ul class="menu menu-horizontal px-1 pr-0 hidden md:flex items-center">
        <li><a>Learn</a></li>
        <li><a>Community</a></li>
        <li><a>Blog</a></li>
        <li class="hidden md:block"><a class="btn bg-blue-950 text-white">Register</a></li>
      </ul>
      <ul class="flex md:hidden mr-6">
        <li><a class="btn bg-blue-950 text-white">Register</a></li>
      </ul>
    </div>
  </header>
</template>
