// smkdev-landing-task1b/src/components/Navbar.jsx
import { useState } from 'react'
import LogoSmkDev from '../assets/logo-smkdev.png'

const Navbar = () => {
    const [isMenuOpen, setIsMenuOpen] = useState(false)

    const toggleMenu = () => {
        setIsMenuOpen(!isMenuOpen)
    }

    return (
        <>
            <nav className="bg-white p-5 fixed w-full text-black z-50">
                <div className='flex justify-between items-center'>
                    <div>
                        <img src={LogoSmkDev} className='h-5' alt="SMK Dev Logo" />
                    </div>
                    <button className='md:hidden text-2xl' onClick={toggleMenu}>
                        {isMenuOpen ? 'X' : '≡'}
                    </button>
                    <div className='hidden md:block'>
                        <ul className='flex gap-8 font-medium'>
                            <li><a className='text-xl' href="#">Learn</a></li>
                            <li><a className='text-xl' href="#">Community</a></li>
                            <li><a className='text-xl' href="#">Blog</a></li>
                        </ul>
                    </div>
                    <div className='hidden md:block'>
                        <a className='px-5 py-3 bg-slate-300 rounded-md font-medium mr-2' href="#">Sign Up</a>
                        <a className='px-5 py-3 bg-slate-300 rounded-md font-medium' href="#">Sign In</a>
                    </div>
                </div>
            </nav>
            {isMenuOpen && (
                <div className='fixed inset-0 bg-white z-40 pt-20 px-5 md:hidden'>
                    <ul className='space-y-4'>
                        <li><a href="#" className="text-xl flex justify-between items-center">Learn <span>›</span></a></li>
                        <li><a href="#" className="text-xl flex justify-between items-center">Community <span>›</span></a></li>
                        <li><a href="#" className="text-xl flex justify-between items-center">Blog <span>›</span></a></li>
                    </ul>
                    <a href='#' className="mt-8 w-full block text-center bg-slate-300 py-3 rounded-md font-medium">
                        Sign In
                    </a>
                    <a href='#' className="mt-4 w-full block text-center bg-slate-300 py-3 rounded-md font-medium">
                        Sign Up
                    </a>
                </div>
            )}
        </>
    )
}

export default Navbar

// src/components/NavBar.vue
<script setup lang="ts">
import MenuIcon from './icons/MenuIcon.vue'
</script>
<template>
  <header class="navbar border-b shadow px-0 md:px-20">
    <div class="dropdown md:hidden">
      <div tabindex="0" role="button" class="btn btn-ghost btn-circle">
        <MenuIcon />
      </div>
      <ul
        tabindex="0"
        class="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] mt-3 w-52 p-2 shadow-xl"
      >
        <li><a>Learn</a></li>
        <li><a>Community</a></li>
        <li><a>Blog</a></li>
      </ul>
    </div>
    <div class="flex-1">
      <a class="btn btn-ghost pl-0">
        <img src="/logo/smkdev-logo.png" alt="logo smkdev" width="120" />
      </a>
    </div>
    <div class="flex-none">
      <ul class="menu menu-horizontal px-1 pr-0 hidden md:flex items-center">
        <li><a>Learn</a></li>
        <li><a>Community</a></li>
        <li><a>Blog</a></li>
        <li class="hidden md:block"><a class="btn bg-blue-950 text-white">Register</a></li>
      </ul>
      <ul class="flex md:hidden mr-6">
        <li><a class="btn bg-blue-950 text-white">Register</a></li>
      </ul>
    </div>
  </header>
</template>
