// frontend-smkdev-task-1b/src/components/Contact.svelte
<script>
    // 
</script>
  <div class="z-10 container mx-auto">
    <div class="flex flex-wrap">
      <div class="w-full md:w-1/2 px-6">
        <div class="flex flex-col justify-between h-full">
          <div class="mb-5 md:max-w-md block">
              <h2 class="text-xl md:text-3xl xl:text-4xl font-bold font-heading tracking-px-n leading-none">Kontak SMKDEV.</h2>
              <p class="mb-6 text-sm text-indigo-600 font-bold uppercase tracking-px">Contact us</p>
              <p class="mb-6 text-sm">Berapa investasi untuk menggunakan SMKDEV? Anda bisa mulai dengan 
               <span class="font-bold"> GRATIS.</span></p>
              <p class="mb-6 text-sm">Silahkan isi form disebelah untuk informasi lebih lanjut.</p>
          </div>    
        </div>
      </div>
      <div class="w-full md:w-1/2">
        <form class="px-6 bg-opacity-80 md:max-w-xl ml-auto rounded-4xl shadow-12xl">
          <label class="block mb-4">
            <p class="mb-2 text-gray-900 font-semibold leading-normal">Nama</p>
            <div class="relative">
              <input class="pl-3 pr-4 py-3 w-full text-gray-500 font-medium placeholder-gray-500 outline-none border border-gray-300 rounded-md focus:ring focus:ring-indigo-300" id="contactInput3-1" type="text" placeholder="First & last name" required>
            </div>
          </label>
          <label class="block mb-4">
            <p class="mb-2 text-gray-900 font-semibold leading-normal">Email</p>
            <div class="relative">
              <input class="pl-3 py-3 w-full text-gray-500 font-medium placeholder-gray-500 outline-none border border-gray-300 rounded-lg focus:ring focus:ring-indigo-300" id="contactInput3-2" type="text" placeholder="Email address" required>
            </div>
          </label>
          <label class="block">
            <p class="mb-2 text-gray-900 font-semibold leading-normal">Pesan</p>
            <div class="relative">
              <textarea class="mb-6 p-4 w-full h-48 font-medium text-gray-500 outline-none placeholder-gray-500 border border-gray-300 resize-none rounded-md focus:ring focus:ring-indigo-300" id="contactInput3-3" placeholder="Write message" required></textarea>
              <div class="md:inline-block">
                <button class="py-2 px-5 lg:w-full text-white font-semibold bg-violet-900 rounded-md  " type="button">Send Message</button>
              </div>
            </div>
          </label>
        </form>
      </div>
    </div>
  </div>

// smkdev_landing_page_firyal/components/Contact.jsx
/*
  This example requires some changes to your config:
  
  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/forms'),
    ],
  }
  ```
*/
"use client";

import { useState } from "react";
import { Field, Label, Switch } from "@headlessui/react";

export default function Contact() {
  const [agreed, setAgreed] = useState(false);

  return (
    <div className="max-w-6xl flex flex-row isolate bg-white mt-60 mb-20">
      <div className="w-1/2 pr-6">
        <h1 className="text-2xl font-bold tracking-tight text-gray-900 sm:text-4xl">
          Kontak SMKDEV
        </h1>
        <p className="mt-2 text-lg leading-8 text-gray-600">
          Berapa investasi untuk menggunakan SMKDEV? Anda bisa mulai dengan
          GRATIS. Silahkan isi form disebelah untuk informasi lebih lanjut.{" "}
        </p>
      </div>
      <form action="#" method="POST" className="mx-auto max-w-xl ">
        <div className="grid grid-cols-1 gap-x-8 gap-y-6 sm:grid-cols-2">
          <div>
            <label
              htmlFor="first-name"
              className="block text-sm font-semibold leading-6 text-gray-900"
            >
              First name
            </label>
            <div className="mt-2.5">
              <input
                id="first-name"
                name="first-name"
                type="text"
                autoComplete="given-name"
                className="block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-[#1c3965] sm:text-sm sm:leading-6"
              />
            </div>
          </div>
          <div>
            <label
              htmlFor="last-name"
              className="block text-sm font-semibold leading-6 text-gray-900"
            >
              Last name
            </label>
            <div className="mt-2.5">
              <input
                id="last-name"
                name="last-name"
                type="text"
                autoComplete="family-name"
                className="block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-[#1c3965] sm:text-sm sm:leading-6"
              />
            </div>
          </div>
          <div className="sm:col-span-2">
            <label
              htmlFor="company"
              className="block text-sm font-semibold leading-6 text-gray-900"
            >
              Company
            </label>
            <div className="mt-2.5">
              <input
                id="company"
                name="company"
                type="text"
                autoComplete="organization"
                className="block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-[#1c3965] sm:text-sm sm:leading-6"
              />
            </div>
          </div>
          <div className="sm:col-span-2">
            <label
              htmlFor="email"
              className="block text-sm font-semibold leading-6 text-gray-900"
            >
              Email
            </label>
            <div className="mt-2.5">
              <input
                id="email"
                name="email"
                type="email"
                autoComplete="email"
                className="block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-[#1c3965] sm:text-sm sm:leading-6"
              />
            </div>
          </div>
          <div className="sm:col-span-2">
            <label
              htmlFor="phone-number"
              className="block text-sm font-semibold leading-6 text-gray-900"
            >
              Phone number
            </label>
            <div className="relative mt-2.5">
              <div className="absolute inset-y-0 left-0 flex items-center">
                <label htmlFor="country" className="sr-only">
                  Country
                </label>
              </div>
              <input
                id="phone-number"
                name="phone-number"
                type="tel"
                autoComplete="tel"
                className="block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-[#1c3965] sm:text-sm sm:leading-6"
              />
            </div>
          </div>
          <div className="sm:col-span-2">
            <label
              htmlFor="message"
              className="block text-sm font-semibold leading-6 text-gray-900"
            >
              Message
            </label>
            <div className="mt-2.5">
              <textarea
                id="message"
                name="message"
                rows={4}
                className="block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-[#1c3965] sm:text-sm sm:leading-6"
                defaultValue={""}
              />
            </div>
          </div>
          <Field className="flex gap-x-4 sm:col-span-2">
            <div className="flex h-6 items-center">
              <Switch
                checked={agreed}
                onChange={setAgreed}
                className="group flex w-8 flex-none cursor-pointer rounded-full bg-gray-200 p-px ring-1 ring-inset ring-gray-900/5 transition-colors duration-200 ease-in-out focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#1c3965] data-[checked]:bg-[#1c3965]"
              >
                <span className="sr-only">Agree to policies</span>
                <span
                  aria-hidden="true"
                  className="h-4 w-4 transform rounded-full bg-white shadow-sm ring-1 ring-gray-900/5 transition duration-200 ease-in-out group-data-[checked]:translate-x-3.5"
                />
              </Switch>
            </div>
            <Label className="text-sm leading-6 text-gray-600">
              By selecting this, you agree to our{" "}
              <a href="#" className="font-semibold text-[#1c3965]">
                privacy&nbsp;policy
              </a>
              .
            </Label>
          </Field>
        </div>
        <div className="mt-10">
          <button className="block w-full rounded-md bg-[#1c3965] px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
            Lets talk
          </button>
        </div>
      </form>
    </div>
  );
}
